### ISSUE TITLE
Low security issue at Dream add forms

### ISSUE THREAD

**Issue by spolischook** [geekhub-php/ck-portal#1]
When you create a dream and add an image, video and docs the name, path and other info sets in hidden forms. For example I can insert in video other link then the preview show.

**Comment by spolischook** [comment]
@monobook так и не пофиксил. 
закрыть ишью нельзя пофиксить.

**Comment by monobook** [comment]
> @monobook так и не пофиксил.
> закрыть ишью нельзя пофиксить.

тебе явно на карантине нечем заняться :)

**Comment by spolischook** [comment]
установил апп гитхаба на телефон и там показует все незакрытые ишью и ПРы

**Comment by monobook** [comment]
@spolischook  https://github.com/geekhub-php/ck-portal/issues/42
