### ISSUE TITLE
Рейтингование / Перестал считаться рейтинг с помощью vk.com

### ISSUE THREAD

**Issue by AlKononenko** [geekhub-php/ck-portal#10]

**Comment by spolischook** [comment]
Проверять рейтинг можно по ссылкам:
http://vk.com/share.php?act=count&index=1&url=http://wikipedia.org&format=json
http://www.odnoklassniki.ru/dk?st.cmd=shareData&ref=http://wikipedia.org&cb=mailru.share.ok.init
http://api.ak.facebook.com/restserver.php?v=1.0&method=links.getStats&urls=http://wikipedia.org&format=json
http://urls.api.twitter.com/1/urls/count.json?url=http://wikipedia.org
