### ISSUE TITLE
Создание мечты / реализовать возможность удалять контрибуты

### ISSUE THREAD

**Issue by AlKononenko** [geekhub-php/ck-portal#18]

**Comment by AlKononenko** [comment]
ДО сейва разумеется

**Comment by spolischook** [comment]
До сейва контрибутить невозможно. Или имеется ввиду статьи кошториса? Дубль https://github.com/geekhub-php/ck-portal/issues/4 ?

**Comment by spolischook** [comment]
duplicate https://github.com/geekhub-php/ck-portal/issues/4
