### ISSUE TITLE
Не выводиться сообщения об отсутствии  информации в категориях  Учасник проектів/Favourites/Повідомлення

### ISSUE THREAD

**Issue by IrinaDiachkova** [geekhub-php/ck-portal#21]
Шаги:
1. Залогинтесь (как новый юзер с чистой историей на сайте) 
2. Зайдите на страницу Мой Профиль
3. Нажмите на кнопки Учасник проектів/Favourites/Повідомлення

Ожидаемый результат:
При отсутствии информации в категориях  Учасник проектів/Favourites/Повідомлення выводиться сообщение по типу "Ви поки що не створили жодної мрії"

Действительный результат:
Пустое место
![13](https://f.cloud.github.com/assets/3994764/356528/96d2dcf2-a10a-11e2-8a49-0950743dd709.PNG)

**Comment by spolischook** [comment]
Функционал не реализован. Можно смотреть в файле эстимейта что реализовано а что нет.
