### ISSUE TITLE
При разном масштабе страницы, элементы располагаются по разному.

### ISSUE THREAD

**Issue by IrinaDiachkova** [geekhub-php/ck-portal#22]
Шаги:
1. Зайдите на любую страницу сайта.
2. Увеличьте и потом уменьшите масштаб отображения сайта.

Ожидаемый результат:
Все элементы страницы остаются на своих местах

Действительный результат:
Все элемента располагаются по разному. 

масштаб 110% и масштаб 125%
![14](https://f.cloud.github.com/assets/3994764/356550/7cf9edf6-a10b-11e2-8af1-4f31f43a3d2a.PNG)
![15](https://f.cloud.github.com/assets/3994764/356551/7fc0bc04-a10b-11e2-932d-266ab73c4766.PNG)

**Comment by spolischook** [comment]
Сейчас пока рано об этом говорить, пока сверстана только главная страница да и то не до конца.
