### ISSUE TITLE
Нет валидации email-a (вводи что хочешь) 

### ISSUE THREAD

**Issue by IrinaDiachkova** [geekhub-php/ck-portal#27]
Шаги:
1. Залогинтесь.
2. Зайдите на страницу Мой профиль
3. Нажмите на Добавить-изменить email
4. Введите любые символы-текст 

Ожидаемый результат:
Сообщение об ошибке

Действительный результат:
Любый символы-текст сохраняются как email (на скриншоте - кириллица, без "@", "." и прочего)
![18](https://f.cloud.github.com/assets/3994764/356727/c5a3ed52-a112-11e2-826d-c541fdc3d3b6.png)

**Comment by AlKononenko** [comment]
Делаем валидацию по следующим параметрам:
1. Только латиница
2. Обязательно наличие @ 
3. Обязательное наличие домена (******.com (me, net, info и т.д.))

Т.е. мейл должен иметь вид my@mail.com 

Эррор месседж - стандартный джаваскриптовый

**Comment by spolischook** [comment]
не актуально, слишком старый ишью.
всем хорошего дня!
