### ISSUE TITLE
Нет валидации номера телефона (вводи что хочешь)

### ISSUE THREAD

**Issue by IrinaDiachkova** [geekhub-php/ck-portal#28]
Шаги:
1. Залогинтесь.
2. Зайдите на страницу Мой профиль
3. Нажмите на Добавить-изменить телефон 
4. Введите любые символы-текст в любом количестве

Ожидаемый результат:
Сообщение об ошибке

Действительный результат:
Любый символы-текст сохраняются как номер телафона (на скриншотах - одна цифра, набор букв, набор спецсимволов)
![19](https://f.cloud.github.com/assets/3994764/356746/d584d0fa-a113-11e2-8098-3faf6ff86333.png)
![20](https://f.cloud.github.com/assets/3994764/356747/d58823f4-a113-11e2-98d3-3287289cd72b.png)
![21](https://f.cloud.github.com/assets/3994764/356748/d59ba6fe-a113-11e2-8c71-fcb35765f70c.png)

**Comment by spolischook** [comment]
Дубль - https://github.com/geekhub-php/ck-portal/issues/6
