### ISSUE TITLE
При смене аватарки кнопки меняют расположение

### ISSUE THREAD

**Issue by IrinaDiachkova** [geekhub-php/ck-portal#29]
Шаги:
1. Залогинтесь
2. Зайдите на страницу Мой профиль
3. Смените аватарку (выбрав картинку правильного размера и расширения)

Ожидаемый результат:
Аватарка изменена, остальные элемента страницы не изменены-не изменили позицию

Действительный результат:
Некоторый кнопки изменили свое расположение (примечание - после перезагрузки страницы она возвращаются на свои места)
![24](https://f.cloud.github.com/assets/3994764/356792/229d0230-a115-11e2-8845-3b91eca2541e.png)
![25](https://f.cloud.github.com/assets/3994764/356793/22b6b8f6-a115-11e2-962c-ebab0e03f0b2.png)

**Comment by spolischook** [comment]
Эта страница еще не сверстана.
