### ISSUE TITLE
Создание мечты / не реализовано добавление документов

### ISSUE THREAD

**Issue by AlKononenko** [geekhub-php/ck-portal#3]
При добавлении документа выводится ошибка File has an invalid mime type, it should be one of application/pdf, application/msword, application/microsoft_word, application/doc, application/rtf, application/xls, application/msexcel.

**Comment by spolischook** [comment]
Профикшено этим комитом https://github.com/geekhub-php/ck-portal/commit/17b41c6cec7689c8d007e18e56987b5993c1c34d
