### ISSUE TITLE
Несоответствие при логине

### ISSUE THREAD

**Issue by IrinaDiachkova** [geekhub-php/ck-portal#32]
Шаги:
1.Не залогинивайтесь.
2. Нажмите на кнопку Додати Мрию.

Ожидаемый результат:
Сообщение типа "только залогиненый юзер может создать мечту. Залогинтесь, пожалуйста" и повтор кнопок для входа - Фб, Вк, Ок.

Действительный результат:
На странице есть поля Имя пользователя и пароль. 

Примечание: насколько я понимаю отдельного пароля для сайта у юзера нет, что тогда вводить пароль от аккаунта соц.сети? Это не кажется разумным. 

![27](https://f.cloud.github.com/assets/3994764/361149/7a62184e-a1b9-11e2-9f5b-f0ecee066cc8.PNG)

**Comment by spolischook** [comment]
Логин и пароль для пользователя генерируется автоматически. Также эта страница используется для автоматических тестов. Страница еще не сверстана, поэтому и выводится стандартный FOSUserBundle страница логина
