### ISSUE TITLE
Нельзя удалить загруженную фотографию-видео-документ (при создании Мечты)

### ISSUE THREAD

**Issue by IrinaDiachkova** [geekhub-php/ck-portal#35]
Шаги:
1. Залогинтесь.
2. Нажмите на кнопку Додати Мрию
3. Нажмите на кнопку Додати Зображення, Додати Видео, Додати Документ
4. Загрузите несколько фотографий, видео, документов

Ожидаемый результат:
Файлы загружены. В верхнем правом углу каждого файла (его виджета на странице) - есть кнопка Удалить (красный крестик как задумывалось), при нажатии на который файл удаляется.

Действительный результат:
Файлы загружены. Кнопки Удалить нет.

**Comment by spolischook** [comment]
Duplicate - https://github.com/geekhub-php/ck-portal/issues/4
