### ISSUE TITLE
Нет отграничения на количество фотографий-видео-документов-тегов (при создании Мечты)

### ISSUE THREAD

**Issue by IrinaDiachkova** [geekhub-php/ck-portal#36]
Шаги:
1. Залогинтесь.
2. Нажмите на кнопку Додати Мрию
3. Нажмите на кнопку Додати Зображення, Додати Видео, Додати Документ, на поле Теги
4. Загрузите несколько фотографий, видео, документов, напишите несколько тегов  (на скриншоте - 23 фотографии, 7 видео, 10 документов, 25 тегов)

Ожидаемый результат:
Файлы загружены. 

Действительный результат:
Файлы загружены, но после загрузки максимального количества файлов выводиться сообщение типа "Извините, нельзя загрузить больше Х количества файлов такого типа"
![28](https://f.cloud.github.com/assets/3994764/361214/78ba4716-a1bc-11e2-8b9f-124013cd1103.PNG)
![29](https://f.cloud.github.com/assets/3994764/361215/78f33fda-a1bc-11e2-9b66-40c622239cda.PNG)

**Comment by AlKononenko** [comment]
Не будем делать ограничение. Здесь вопрос адекватности овнера. Если он добавит 10 реально в тему видео (фото, документов) - на здоровье, дизайн нам это позволяет. Если это будет 10 бредовостей - админ это завернет при премодерации (у нас же не сразу же мрии попадают в паблик)

**Comment by spolischook** [comment]
ок
