### ISSUE TITLE
Нет ограничения на количество символов в тегах (при создании Мечты)

### ISSUE THREAD

**Issue by IrinaDiachkova** [geekhub-php/ck-portal#38]
Шаги:
1. Залогинтесь.
2. Нажмите на кнопку Додати Мрию
3. Нажмите на поле Теги
4. Ведите большое количество символов (без пробела), потом нажмите пробел (на скриншоте теги по 55, 75 и 1 символ)

Ожидаемый результат:
Тег  не создан - сообщение об ограничении количества символов в одном теге.

Действительный результат:
Тег создан. 

![30](https://f.cloud.github.com/assets/3994764/361318/f5088622-a1bf-11e2-9991-d3c77c2a3811.PNG)

**Comment by AlKononenko** [comment]
Не ставим ограничение. Я проверял на changeby.us - там нету.

**Comment by spolischook** [comment]
ок
