### ISSUE TITLE
Нет отграничения на количество статей в  каждом пункте Сметы

### ISSUE THREAD

**Issue by IrinaDiachkova** [geekhub-php/ck-portal#40]
Шаги:
1. Залогинтесь.
2. Нажмите на кнопку Додати Мрию
3. Нажмите на кнопку Додати Статтю в блоке Смета (под всеми тремя заголовками Фінансові витрати, Інструменти / обладнання / техніка, Роботи та ресурси)
4. Создайте большое количество статей 

Ожидаемый результат:
После достижения максимального количества статей в каждом из трех пунктов Сметы дальше нельзя добавлять новые статьи и показывается сообщения об ошибке.

Действительный результат:
Статья создана (на скриншоте - у одного из пунктов создано 45 статей)

![32](https://f.cloud.github.com/assets/3994764/361379/114f60b0-a1c2-11e2-99b3-ee95171166c1.PNG)

**Comment by spolischook** [comment]
Давайте так. Если вы пишете о максимальном количестве то указывайте его. Это важно. Нельзя просто писать максимальное количество, это обязательно должно быть какоето число.

**Comment by spolischook** [comment]
fix https://github.com/geekhub-php/ck-portal/commit/861d78a99393178d5c5d4d35f54999b0a760d266
