### ISSUE TITLE
Баг з авторизаціею через facebook

### ISSUE THREAD

**Issue by AlKononenko** [geekhub-php/ck-portal#42]
Кроки:
1. Залогінтесь.
2. Нажміть на кнопку Авторизуватись через вконтакті
3. Зайдіть у свій профіль
4. Зредагуйте свій e-mail. Використайте той самий e-mail на який зареєстровано акаунт у FB.
5. Вийдіть
6. Нажміть на кнопку Авторизуватись через FaceBook

Очікуємий результат:
Аккаунти змержаться т.я. два акаунти не можуть мати один і той самий e-mail

Действительный результат:
БІДА!!!!!
![IMG_15042013_155648](https://f.cloud.github.com/assets/1978331/380838/a44ef47a-a5d2-11e2-8e39-e7ac7296e487.png)

**Comment by monobook** [comment]
тут еще
