### ISSUE TITLE
Создание мечты / убрать "Теги" из обязательных при заполнении полей

### ISSUE THREAD

**Issue by AlKononenko** [geekhub-php/ck-portal#6]

**Comment by spolischook** [comment]
и не страшно что никто в таком случае теги проставлять не будет? не?

**Comment by AlKononenko** [comment]
Абсолютно не, это вспомагательное поле для прохаваных юзеров. Влияет только на поиск. Никогда теги не делаются обязательными полями.

**Comment by spolischook** [comment]
"Никогда теги не делаются обязательными полями."
Никогда не говори никогда. На некоторых весьма значительных сайтах это поле обязательное.
Так то так.

**Comment by AlKononenko** [comment]
Не страшно :) У нас это исключительно хелп функционал, он не реквайеред.

**Comment by spolischook** [comment]
fix https://github.com/geekhub-php/ck-portal/commit/8b94112b7f59b165729f3dad382fcd871309a0b4
